[package]
name = "gc_log_analyzer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gca"
path = "src/main.rs"

[dependencies]
chrono = {version = "0.4.41", features = ["serde"]}
serde = {version = "1.0.219", features = ["derive"]}
